<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProductsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255)->nullable();
            $table->integer('category_id')->nullable();
            $table->integer('stock')->nullable();
            $table->double('buy_price')->nullable();
            $table->double('sell_price')->nullable();
            $table->double('discount_price')->nullable()->default(0);
            $table->string('sku', 255)->nullable();
            $table->string('barcode', 255)->nullable()->default('');
            $table->tinyInteger('is_damaged')->nullable()->default(0);
            $table->tinyInteger('is_lost')->nullable()->default(0);
            $table->tinyInteger('is_expired')->nullable()->default(0);
            $table->text('remark')->nullable();
            $table->nullableTimestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
}
